import test from "node:test";
import assert from "node:assert/strict";

import { PRINT_ERROR_CATALOGUE, PRINT_ERROR_CATALOGUES, printErrorHex, describePrintError, describePrintErrorInAll } from "../src/printerrors.js";

test("the shipped catalogue is well formed", () => {
    // Regenerated by scripts/fetch-print-errors.js; these are the invariants
    // the lookup relies on rather than the contents, which are Bambu Lab's.
    assert.ok(Number.isInteger(PRINT_ERROR_CATALOGUE.version));
    assert.ok(PRINT_ERROR_CATALOGUE.models.includes("P2S"));

    const entries = Object.entries(PRINT_ERROR_CATALOGUE.errors);
    assert.ok(entries.length > 900, `${entries.length} codes`);
    for (const [code, text] of entries) {
        assert.match(code, /^[0-9A-F]{8}$/, code);
        assert.ok(typeof text === "string" && text.trim() === text && text.length > 0, code);
    }
});

test("the number a printer reports is the hex code the catalogue is keyed by", () => {
    // 50348044 is what a P2S reports for a print stopped by hand
    assert.equal(printErrorHex(50348044), "0300400C");
    assert.equal(printErrorHex("50348044"), "0300400C");
    // Already hex, as a log line or a bug report carries it
    assert.equal(printErrorHex("0300400c"), "0300400C");
    // Not a code
    assert.equal(printErrorHex(0), null);
    assert.equal(printErrorHex("0"), null);
    assert.equal(printErrorHex(null), null);
    assert.equal(printErrorHex("nonsense"), null);
    assert.equal(printErrorHex(-1), null);
    assert.equal(printErrorHex(0x1_0000_0000), null);
});

test("a known code gets its sentence, an unknown one nothing", () => {
    assert.equal(describePrintError(50348044), "The task was canceled.");
    assert.equal(describePrintError("0300400C"), "The task was canceled.");
    assert.equal(describePrintError(7), null);
    assert.equal(describePrintError(null), null);
});

test("the catalogue is shipped in German too, and a missing language falls back to English", () => {
    assert.ok(PRINT_ERROR_CATALOGUES.de);
    assert.equal(describePrintError(50348044, "de"), "Die Aufgabe wurde abgebrochen.");
    assert.equal(describePrintError(50348044, "xx"), "The task was canceled.");
    assert.deepEqual(describePrintErrorInAll(50348044), { en: "The task was canceled.", de: "Die Aufgabe wurde abgebrochen." });
    assert.equal(describePrintErrorInAll(7), null);
});

test("a print error is handed out as parts a client can word itself", async () => {
    const { printErrorDetails, printErrorText } = await import("../src/mqtt.js");
    // A P2S stopped by hand
    const stopped = { print_error: 50348044, fail_reason: "50348044" };
    assert.equal(printErrorText(stopped), "Printer error 50348044: The task was canceled.");
    assert.deepEqual(printErrorDetails(stopped), [{ kind: "printer", code: "50348044", texts: { en: "The task was canceled.", de: "Die Aufgabe wurde abgebrochen." } }]);
    assert.deepEqual(printErrorDetails({ print_error: 0, fail_reason: "7" }), [{ kind: "fail", code: "7", texts: null }]);
    assert.equal(printErrorDetails({ print_error: 0, fail_reason: "0" }), null);
});
