services:
  haspelsync:
    image: ghcr.io/rdiger-36/haspelsync:dev
    container_name: haspelsync
    ports:
      - 4000:4000
    environment:
      - TZ=Europe/Berlin
    volumes:
      - ./haspelsync/config/printers:/app/printers
      - ./haspelsync/config/logs:/app/logs
    restart: unless-stopped
