/**
 * The SpoolmanDB filament catalogue the mock Spoolman serves on
 * `/api/v1/external/filament`.
 *
 * Copied verbatim from https://donkie.github.io/SpoolmanDB/filaments.json, so
 * the ids, densities, temperatures and above all the colour sets are the real
 * ones the service matches against. The colours agree with the three Bambu Lab
 * hex code tables for PLA Silk Multi-Color, PLA Basic Gradient and TPU 90A.
 *
 * Deliberately a subset. `findMatchingExternalFilament()` reduces a material
 * name to its first word, so "PLA Silk" and "PLA Basic Gradient" both search
 * the `bambulab_pla` prefix and only the colour set separates the entries. The
 * full catalogue holds several thousand of them, and a fixture that decides
 * which one is found is worth more here than a complete one.
 *
 * `multi_color_direction` is the field the UI needs to draw a colour set: a
 * "longitudinal" filament fades from one colour into the next along its
 * length, a "coaxial" one carries them side by side down the strand.
 */
export const CATALOGUE = [
    {
        id: "bambulab_pla_gildedrose(pink-gold)_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Gilded Rose (Pink-Gold)",
        material: "PLA",
        density: 1.32,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["FF9425", "FCA2BF"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "coaxial",
    },
    {
        id: "bambulab_pla_bluehawaii(blue-green)_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Blue Hawaii (Blue-Green)",
        material: "PLA",
        density: 1.32,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["60A4E8", "4CE4A0"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "coaxial",
    },
    {
        id: "bambulab_pla_midnightblaze(blue-red)_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Midnight Blaze (Blue-Red)",
        material: "PLA",
        density: 1.32,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["0047BB", "7D1B49"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "coaxial",
    },
    {
        id: "bambulab_pla_neoncity(blue-magenta)_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Neon City (Blue-Magenta)",
        material: "PLA",
        density: 1.32,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["0047BB", "BB22A3"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "coaxial",
    },
    {
        id: "bambulab_pla_velveteclipse(black-red)_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Velvet Eclipse (Black-Red)",
        material: "PLA",
        density: 1.32,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["000000", "A34342"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "coaxial",
    },
    {
        id: "bambulab_pla_aurorapurple(blue-purple)_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Aurora Purple (Blue-Purple)",
        material: "PLA",
        density: 1.32,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["1E63BF", "713D9C"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_pla_arcticwhisper_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Arctic Whisper",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["9CDBD9", "FFFFFF"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_pla_oceantomeadow_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Ocean to Meadow",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["307FE2", "54FF9B"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_pla_cottoncandycloud_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Cotton Candy Cloud",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["E7C1D5", "8EC9E9"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_pla_blueberrybubblegum_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Blueberry Bubblegum",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["6FCAEF", "8573DD"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_pla_mintlime_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Mint Lime",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["B6FF43", "4EC939"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_pla_solarbreeze_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Solar Breeze",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["E94B3C", "FFFFFF"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_pla_pinkcitrus_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Pink Citrus",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["F78F77", "E4505A"],
        extruder_temp: 220,
        bed_temp: 40,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_tpu-90a_blaze_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Blaze",
        material: "TPU-90A",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["F1AAA8", "D21B3C"],
        extruder_temp: 230,
        bed_temp: 30,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_tpu-90a_frozen_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Frozen",
        material: "TPU-90A",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: null,
        color_hexes: ["FFFFFF", "40B6E4"],
        extruder_temp: 230,
        bed_temp: 30,
        multi_color_direction: "longitudinal",
    },
    {
        id: "bambulab_tpu-90a_black_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Black",
        material: "TPU-90A",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: "000000",
        color_hexes: null,
        extruder_temp: 230,
        bed_temp: 30,
        multi_color_direction: null,
    },
    {
        id: "bambulab_tpu-90a_white_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "White",
        material: "TPU-90A",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: "FFFFFF",
        color_hexes: null,
        extruder_temp: 230,
        bed_temp: 30,
        multi_color_direction: null,
    },
    {
        id: "bambulab_pla_black_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Black",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: "000000",
        color_hexes: null,
        extruder_temp: 220,
        bed_temp: 60,
        multi_color_direction: null,
    },
    {
        id: "bambulab_pla_jadewhite_1000_175_n",
        manufacturer: "Bambu Lab",
        name: "Jade White",
        material: "PLA",
        density: 1.24,
        weight: 1000,
        spool_weight: 250,
        diameter: 1.75,
        color_hex: "FFFFFF",
        color_hexes: null,
        extruder_temp: 220,
        bed_temp: 60,
        multi_color_direction: null,
    },];

/** The material catalogue behind `/api/v1/external/material`. */
export const EXTERNAL_MATERIALS = [
    { material: "PLA", density: 1.24, extruder_temp: 220, bed_temp: 60 },
    { material: "TPU", density: 1.24, extruder_temp: 230, bed_temp: 30 },
    { material: "PETG", density: 1.27, extruder_temp: 255, bed_temp: 70 },
];
